import { MainNavItem, SidebarNavItem } from '@/types/nav';

import { docsConfig } from '../docs-config';

interface DocsConfig {
  mainNav: MainNavItem[];
  sidebarNav: SidebarNavItem[];
}

export const reactDocsConfig: DocsConfig = {
  mainNav: docsConfig.mainNav,
  sidebarNav: [
    {
      title: '🌱 React Basics',
      items: [
        {
          title: 'click handler',
          description: 'Reactでクリック時に処理を実行するサンプル',
          slug: 'clickHandler',
          href: '/tech/react/clickHandler',
          items: [],
          label: '',
        },
        {
          title: 'input',
          description: 'Reactで入力時に処理を実行するサンプル',
          slug: 'input',
          href: '/tech/react/input',
          items: [],
          label: '',
        },
        {
          title: 'hover',
          description: 'Reactでマウスオーバー時に処理を実行するサンプル',
          slug: 'hover',
          href: '/tech/react/hover',
          items: [],
          label: '',
        },
        {
          title: 'useState',
          description: 'ReactでuseStateを使用するサンプル',
          slug: 'useState',
          href: '/tech/react/useState',
          items: [],
          label: '',
        },
        {
          title: 'multiple states',
          description: 'Reactで複数のuseStateを使用するサンプル',
          slug: 'multipleState',
          href: '/tech/react/multipleState',
          items: [],
          label: '',
        },
        {
          title: 'state of object',
          description: 'ReactでObjectを扱うサンプル',
          slug: 'stateObject',
          href: '/tech/react/stateObject',
          items: [],
          label: '',
        },
        {
          title: 'state of array',
          description: 'Reactで配列を扱うサンプル',
          slug: 'stateArray',
          href: '/tech/react/stateArray',
          items: [],
          label: '',
        },
        {
          title: 'state and props',
          description: 'Reactでstateとpropsを扱うサンプル',
          slug: 'stateAndProps',
          href: '/tech/react/stateAndProps',
          items: [],
          label: '',
        },
      ],
    },
    {
      title: '🦋 React Intermediate - 1',
      items: [
        {
          title: 'list component',
          description: 'Reactでリストを表示するサンプル',
          slug: 'listComponent',
          href: '/tech/react/listComponent',
          items: [],
          label: '',
        },
        {
          title: 'list and filter',
          description: 'Reactでリストをフィルターして表示するサンプル',
          slug: 'listAndFilter',
          href: '/tech/react/listAndFilter',
          items: [],
          label: '',
        },
        {
          title: 'input and textarea',
          description: 'Reactで入力とテキストエリアを表示するサンプル',
          slug: 'inputTextarea',
          href: '/tech/react/inputTextarea',
          items: [],
          label: '',
        },
        {
          title: 'radio',
          description: 'Reactでラジオボタンを表示するサンプル',
          slug: 'radio',
          href: '/tech/react/radio',
          items: [],
          label: '',
        },
        {
          title: 'single checkbox',
          description: 'Reactでチェックボックスを表示するサンプル',
          slug: 'singleCheckbox',
          href: '/tech/react/singleCheckbox',
          items: [],
          label: '',
        },
        {
          title: 'multi checkbox',
          description: 'Reactで複数のチェックボックスを表示するサンプル',
          slug: 'multiCheckbox',
          href: '/tech/react/multiCheckbox',
          items: [],
          label: '',
        },
        {
          title: 'select',
          description: 'Reactでセレクトボックスを表示するサンプル',
          slug: 'select',
          href: '/tech/react/select',
          items: [],
          label: '',
        },
        {
          title: 'reminder',
          description: 'Reactでリマインダーを表示するサンプル',
          slug: 'reminder',
          href: '/tech/react/reminder',
          items: [],
          label: '',
        },
        {
          title: 'dialog',
          description: 'Reactでダイアログを表示するサンプル',
          slug: 'dialog',
          href: '/tech/react/dialog',
          items: [],
          label: '',
        },
        {
          title: 'useRef',
          description: 'ReactでuseRefを使用するサンプル',
          slug: 'useRef',
          href: '/tech/react/useRef',
          items: [],
          label: '',
        },
        {
          title: 'forwardRef',
          description: 'ReactでforwardRefを使用するサンプル',
          slug: 'forwardRef',
          href: '/tech/react/forwardRef',
          items: [],
          label: '',
        },
        {
          title: 'useReducer',
          description: 'ReactでuseReducerを使用するサンプル',
          slug: 'useReducer',
          href: '/tech/react/useReducer',
          items: [],
          label: '',
        },
        {
          title: 'useContext',
          description: 'ReactでuseContextを使用するサンプル',
          slug: 'useContext',
          href: '/tech/react/useContext',
          items: [],
          label: '',
        },
        {
          title: 'useContext with state',
          description: 'ReactでuseStateとuseContextを使用するサンプル',
          slug: 'useContextWithState',
          href: '/tech/react/useContextWithState',
          items: [],
          label: '',
        },
        {
          title: 'context file',
          description: 'ReactでContextファイルを使用するサンプル',
          slug: 'contextFile',
          href: '/tech/react/contextFile',
          items: [],
          label: '',
        },
        {
          title: 'context file render',
          description: 'ReactでContextファイルをレンダリングするサンプル',
          slug: 'contextFileRender',
          href: '/tech/react/contextFileRender',
          items: [],
          label: '',
        },
        {
          title: 'context with reducer',
          description: 'ReactでContextとreducerを使用するサンプル',
          slug: 'contextWithReducer',
          href: '/tech/react/contextWithReducer',
          items: [],
          label: '',
        },
        {
          title: 'useEffect init',
          description: 'ReactでuseEffectを初期化するサンプル',
          slug: 'useEffectInit',
          href: '/tech/react/useEffectInit',
          items: [],
          label: '',
        },
        {
          title: 'useEffect update',
          description: 'ReactでuseEffectを更新するサンプル',
          slug: 'useEffectUpdate',
          href: '/tech/react/useEffectUpdate',
          items: [],
          label: '',
        },
        {
          title: 'useLayoutEffect',
          description: 'ReactでuseLayoutEffectを使用するサンプル',
          slug: 'useLayoutEffect',
          href: '/tech/react/useLayoutEffect',
          items: [],
          label: '',
        },
        {
          title: 'useEffect and click',
          description: 'ReactでuseEffectとクリックを使用するサンプル',
          slug: 'useEffectClick',
          href: '/tech/react/useEffectClick',
          items: [],
          label: '',
        },
        {
          title: 'custom hook',
          description: 'Reactでカスタムフックを使用するサンプル',
          slug: 'customHook',
          href: '/tech/react/customHook',
          items: [],
          label: '',
        },
      ],
    },
    {
      title: '🐦 React Intermediate - 2',
      items: [
        {
          title: 'memo',
          description: 'Reactでメモを使用するサンプル',
          slug: 'memo',
          href: '/tech/react/memo',
          items: [],
          label: '',
        },
        {
          title: 'useCallback',
          description: 'ReactでuseCallbackを使用するサンプル',
          slug: 'useCallback',
          href: '/tech/react/useCallback',
          items: [],
          label: '',
        },
        {
          title: 'useCallback deps',
          description: 'ReactでuseCallbackのdepsを使用するサンプル',
          slug: 'useCallbackDeps',
          href: '/tech/react/useCallbackDeps',
          items: [],
          label: '',
        },
        {
          title: 'useMemo',
          description: 'ReactでuseMemoを使用するサンプル',
          slug: 'useMemo',
          href: '/tech/react/useMemo',
          items: [],
          label: '',
        },
        {
          title: 'useTransition',
          description: 'ReactでuseTransitionを使用するサンプル',
          slug: 'useTransition',
          href: '/tech/react/useTransition',
          items: [],
          label: '',
        },
        {
          title: 'useDeferredValue',
          description: 'ReactでuseDeferredValueを使用するサンプル',
          slug: 'useDeferredValue',
          href: '/tech/react/useDeferredValue',
          items: [],
          label: '',
        },
        {
          title: 'dynamic import',
          description: 'ReactでDynamic Importを使用するサンプル',
          slug: 'dynamicImport',
          href: '/tech/react/dynamicImport',
          items: [],
          label: '',
        },
        {
          title: 'react lazy',
          description: 'Reactでlazyを使用するサンプル',
          slug: 'reactLazy',
          href: '/tech/react/reactLazy',
          items: [],
          label: '',
        },
      ],
    },
  ],
};

/**
 * Reactのドキュメントの全ての項目
 */
export const reactDocsAllItems = reactDocsConfig.sidebarNav.flatMap((section) => section.items);
