import type { CodegenConfig } from '@graphql-codegen/cli';

const codegenConfig: CodegenConfig = {
  overwrite: true,
  schema: 'apps/api/dist/autogenerated-schema.gql',
  documents: ['apps/web/src/**/*.ts', 'apps/web/src/**/*.tsx'],
  generates: {
    'apps/web/src/gql/': {
      preset: 'client',
      plugins: [],
      config: {},
    },
  },
};

export default codegenConfig;
